[package]
name = "sentry-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sentry-core = { path = "../sentry-core" }
sentry-telepresence = { path = "../sentry-telepresence" }
serde = { workspace = true }
serde_json = { workspace = true }
colored = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
